- .eslintrc.js
- src/alto-ui/Button/Button.js
- src/alto-ui/Button/Button.scss
- src/alto-ui/Button/story.js
- src/alto-ui/Form/CheckBox/story.js
- src/alto-ui/Form/FormElement/FormElement.js
- src/alto-ui/Form/FormElement/FormElement.scss
- src/alto-ui/Form/Label/Label.js
- src/alto-ui/Form/Label/Label.scss
- src/alto-ui/Form/Label/README.md
- src/alto-ui/Form/Label/index.js
- src/alto-ui/Form/Label/story.js
- src/alto-ui/Form/TextArea/TextArea.js
- src/alto-ui/Form/TextField/TextField.js
- src/alto-ui/Form/TextField/TextField.scss
- src/alto-ui/Form/TextField/story.js
- src/alto-ui/Form/story.js
- src/alto-ui/SideNav/SideNav.js
- src/alto-ui/SideNav/SideNav.scss
- src/alto-ui/Tabs/Tabs.js
- src/alto-ui/Tabs/story.js
- src/alto-ui/helpers/bem.js
- Lowercase SideNav classNames + close menu onClick item on narrow
- Add panel prop to tabs
- Switch TextField and TextArea to scss
- Update linter, disable label nesting a11y rule
- Use scss for FormElement and create a Label component
- Create readOnly on TextField/Area
- fix uncentered stories
- fix button danger color
- fix button block
- Add Link as Button thanks to href
> ReadOnly TextField/Area + some migrations to sass + fixes

- src/alto-ui/Icons/Icon.scss
- src/alto-ui/SideNav/SideNav.scss
- IE11 does not support css value initial so icon buttons fallback to other rule
- Horizontal scroll bar appears when SideNav collapsed
> ie11 proposed solutions

- src/alto-ui/Tree/components/TreeItem/TreeItem.js
- src/alto-ui/Tree/components/TreeItem/TreeItem.scss
If Tree Item is not interactive, remove the hovering style and cursor
> non-interactive tree items should not have hover style

- src/alto-ui/Alert/Alert.scss
Darkened text for the following alerts:
- Default
- Success
- Warning
> Increased contrast of alerts to improve a11y

- src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
- src/alto-ui/Form/CheckBox/CheckBox.scss
- src/alto-ui/Form/Radio/Radio.scss
- src/alto-ui/Form/Select/Select.scss
- src/alto-ui/Form/TextField/TextField.scss
- src/alto-ui/scss/variables.scss
> Increase contrast for input fields

- src/alto-ui/Icons/Icon.scss
> Darkened icon buttons

- src/alto-ui/Datagrid/Datagrid.js
- src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.scss
- limit resize of frozen area in order to not block scrollable area
- crop dropdowns if columns is too thin
> fixes datagrid resize

- src/alto-ui/Overlay/Overlay.js
- src/alto-ui/Portal.js
Portal will render children in a React Portal => outside of the default root dom node. If no root is provided, it will append the content at the end of the body.
> Create a Portal component + use it in Overlay

- src/alto-ui/Overlay/Overlay.js
- src/alto-ui/Overlay/OverlayContainer.js
- src/alto-ui/Overlay/index.js
- src/alto-ui/scss/variables.scss
The idea is that if an overlay is created inside an another one (a dropdown inside a modal for example) , it will disable (forcing `inert` prop) its parent overlays. So you can only close one overlay at a time (the last open one).
> Create a OverlayContext to disable parent overlays

- .eslintrc.js
- .prettierrc
- src/alto-ui/Datagrid/Datagrid.js
Added also the .prettierrc config and .eslint line-break style to avoid Mac - Windows line break conflict
> 34695 - recalculate height of freeze table on window.resize event

- src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
- src/alto-ui/Form/InputNumber/InputNumber.js
According to @andymcfee decision, input number shouldn't have forced right align by default. That align should be set only where is needed
> remove default right number input text align

- package.json
- src/alto-ui/hooks/useFocusInOut.js
- take at least 2 param: a callback, and at least one ref (other params is for optional additionnal refs)
- call the callback each time the ref(s) receive the focus or loose it (works with children)
- usefull to create a element that can have a "active" state
- return focuses state (callback is not mandatory, can be pass as null and you can use just the returned state)
> add useFocusInOut hook

- src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.scss
On focus, the number inputs in grids with wide columns would shrink.
> BQM-135 Fix number input shrinking on wide columns in grids

- src/alto-ui/Datagrid/Datagrid.js
- src/alto-ui/Datagrid/Datagrid.scss
- Fixed misalignment of grid rows caused by the grouped summary row's checkbox placeholder
- Fixed all three row density size settings
- Fixed issue where the summary row checkbox placeholder was sizing incorrectly at `default` and `compact` density settings
> Fix misalignment of checkboxes in grouped grids

- src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
Previous PR remove two props on list:
```
- onOpen: this.handleStartEditing,
- clearable: true,
```
> bugfix Datagrid : manage onOpen event on list

- src/alto-ui/Form/RichTextEditor/RichTextEditor.js
- src/alto-ui/HTMLBlock/HTMLBlock.js
- src/alto-ui/scss/index.scss
- src/alto-ui/scss/libs.scss
Move Quill css files to an external scss/libs file to ensure the will be loaded once and first.
> Ensure Quill css can be overridden

- src/alto-ui/HTMLBlock/HTMLBlock.js
- src/alto-ui/HTMLBlock/context.js
The goal is to allow users to pass the same props more easily to all HTMLBlock in the tree. Same renderMentions for example. It's like a `shared props provider`.
> Create a context for HTMLBlock

- src/alto-ui/Form/FormElement/FormElement.js
Use new HTMLBlock for helpText in FormElement.
> Use HTMLBlock in FormElement for helpText

- .storybook/config.js
- src/alto-ui/Actions/Actions.js
- src/alto-ui/Actions/Actions.scss
- src/alto-ui/Actions/index.js
- src/alto-ui/Actions/story.js
- src/alto-ui/Group/CleanGroupContext.js
- src/alto-ui/Group/Group.js
- src/alto-ui/Group/Group.scss
- src/alto-ui/Group/GroupItem.js
- src/alto-ui/Group/context.js
- src/alto-ui/Group/index.js
Group is used to create a "Group" context. Then if you create a component that can be grouped, you will be able to guess if you are in a group and in which position. Needed for list, button group...
Actions is a group of icons that if you get more than the defined max number ut turns into a dropdown.
max: 3, actions: 2 | max: 3, actions: 3 | max: 2, actions: 3
-|-|-
> Add Actions and Group

- src/alto-ui/Form/Switch/Switch.js
- src/alto-ui/Form/Switch/Switch.scss
- src/alto-ui/Form/Switch/story.js
- src/alto-ui/List/List.js
`onChange(e)` -> `onChange(value)`
> change siwtch `onChange` signature

- src/alto-ui/List/List.js
You can now pass a function to cutomize the rendering of a list element.
No visual change.
> Add a custom list item renderer

- src/alto-ui/Group/Group.js
- src/alto-ui/List/List.js
- src/alto-ui/List/List.scss
- src/alto-ui/List/story/Backlog.js
- src/alto-ui/List/story/Simple.js
- src/alto-ui/List/story/SimpleDemo.js
- src/alto-ui/List/story/index.js
- src/alto-ui/Sortable/Sortable.js
- src/alto-ui/helpers/getItemKey.js
- change behavior of `itemKey` prop if nothing is provided. This is taken into account in List, Group and Sortable.
- New "Simple" story in List (just passing an array of string as items)
- New "Nested custom" story in List
- add `hover` state to list (works like `active`)
No visual changes
> Better default "itemKey" + stories of List

- src/alto-ui/Datagrid/components/DatagridGroupedRow/DatagridGroupedRow.js
Allow to define a custom renderer for grops thanls to a renderGroupCell function.
> Add renderGroupCell to Datagrid

- src/alto-ui/Form/TextField/TextField.scss
> IE11 : drop down list icon not displayed

- src/alto-ui/List/List.js
Add second param to onChange on List with actual changed item - helpfull if you want to get only changed item f.eg. id from list item with checkbox or switch.
> bugfix/Add second param to onChange with changed item

- src/alto-ui/List/List.js
Fix checkbox and switch change state in Alto LIst. 
Those components are rendered in List and get `value` for `checked` property. 
Sometimes value in alto lists for a quick time becomes null so React doesn't know that this is controlled or uncontrolled input. 
More description of the issue: https://stackoverflow.com/questions/53071743/react-a-component-is-changing-an-uncontrolled-input-of-type-checkbox-to-be-contr
> bugfix/Fix checkbox and switch on List

- src/alto-ui/SideNav/SideNav.scss
Change color of links in Side nav to $coolgrey-80
> bugfix/Change Side Nav links color for light theme

- src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
- src/alto-ui/Form/TextField/TextField.scss
- src/alto-ui/Form/Typeahead/Typeahead.scss
Fix for fields components that use Typeahead  on InternetExplorer + align text in cell Datagrid
> bugfix/Fix typeahead text fields on IE

- src/alto-ui/List/List.js
Fix invoke props function with different values for List with badges
Please check invoke this functions few lines above: 
```
const props =
typeof field.props === 'function' ? field.props(data, item, itemIndex) : field.props; 
```
> Fix invoke props function in list with badges

- src/alto-ui/Datagrid/Datagrid.js
In datagrid, if there is no frozen columns, dont render the "frozen areas".
> Dont render frozen areas if no frozen cols is provided

- src/alto-ui/Form/DatePicker/DatePicker.js
Date picker input field was not clearable.
Now on click [x] the field can be clear.
> bugfix - fixed clear input for datepicker

- src/alto-ui/List/List.js
IE11 wrong calculate height of a content for element suses overflow-y and we need additional element without overflow css rule.
> bugfix fixed read height of grid list in IE11

- src/alto-ui/Datagrid/Datagrid.js
display grouped rows only if the columns groupedby is displayed
> bugfix DatagridRows: display is broken when column groupedby is not visible

- src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
> Bugfix - Active row needs to have white inputs

- src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
- src/alto-ui/Form/Typeahead/Typeahead.js
Removed isDataGridCell prop from typeahead, removed onClose if onBlur
BUG: When clicking on the RemoveIcon it was forcing onClose
> Remove onClose on onBlur

- src/alto-ui/Datagrid/Datagrid.scss
horizontal scroll is not needed for grid if grid is too short
> horizontal scroll is not needed for grid if grid is too short

- src/alto-ui/Datagrid/Datagrid.js
hotfix - in some cases if data wasn't ready yet node for scroll listener doesn't exists and throws error
> hotfix - error add event listener on datagrid

- src/alto-ui/ButtonGroup/ButtonGroup.scss
Buttons in button group are now displayed in blue-50 on mouse hover.
> Add hover state on button group

- src/alto-ui/Datagrid/components/DatagridResizer/DatagridResizer.js
- src/alto-ui/Datagrid/components/DatagridResizer/__tests__/DatagridResizer.test.js
It needed to upgrade React at least to v16.8.5 in which was fixed created to working with shallow and useState
> ennhancement - refactor DatagridResizer to func component

- src/alto-ui/Datagrid/Datagrid.js
- src/alto-ui/Datagrid/__tests__/Datagrid.test.js
- src/alto-ui/Datagrid/components/DatagridCellInput/__tests__/DatagridCellInput.test.js
- src/alto-ui/Datagrid/components/DatagridHead/DatagridHead.js
- src/alto-ui/Datagrid/components/DatagridHeaderCell/DatagridHeaderCell.js
- src/alto-ui/Datagrid/components/DatagridHeaderCell/__tests__/DatagridHeaderCell.test.js
- src/alto-ui/Datagrid/components/DatagridHeaderRow/DatagridHeaderRow.js
- src/alto-ui/Datagrid/components/DatagridResizer/DatagridResizer.js
> enhancement - move DatagridResizer to DatagridHead
