README.md
src/Button/Button.js

Changed the disabled button color from $grey-50 to $grey-30.

Disable button color

---

.storybook/config.js
src/alto-ui/Breadcrumb/Breadcrumb.js
src/alto-ui/Breadcrumb/Breadcrumb.scss
src/alto-ui/Breadcrumb/README.md
src/alto-ui/Breadcrumb/index.js
src/alto-ui/Breadcrumb/story.js
src/alto-ui/scss/placeholders.scss
src/alto-ui/scss/utilities/typography.scss

Breadcrumb

---

.storybook/config.js
src/alto-ui/Avatar/Avatar.js
src/alto-ui/Avatar/Avatar.scss
src/alto-ui/Avatar/README.md
src/alto-ui/Avatar/avatar.scss
src/alto-ui/Avatar/index.js
src/alto-ui/Avatar/story.js
src/alto-ui/Icons/User.js
src/alto-ui/Icons/story.js
src/alto-ui/Image.js
src/alto-ui/Link.js
src/alto-ui/List/List.js
src/alto-ui/List/List.scss
src/alto-ui/List/story.js
src/alto-ui/scss/_components.scss

List & Avatar

---

.storybook/config.js
src/alto-ui/Avatar/Avatar.scss
src/alto-ui/Breadcrumb/Breadcrumb.js
src/alto-ui/Breadcrumb/Breadcrumb.scss
src/alto-ui/Form/FormElement/FormElement.js
src/alto-ui/Form/Select/Select.js
src/alto-ui/Icons/Eye.js
src/alto-ui/Icons/story.js
src/alto-ui/List/List.scss
src/alto-ui/SideNav/SideNav.js
src/alto-ui/SideNav/SideNav.scss
src/alto-ui/SideNav/story.js
src/alto-ui/Table/README.md
src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/index.js
src/alto-ui/Table/story.js
src/alto-ui/scss/variables.scss

- Add Table component
- Add Eye icon
- severals fixes and improvements

Improved Breadcrumbs and mobile nav

---

src/alto-ui/Button/Button.scss
src/alto-ui/scss/variables.scss
src/app/content/components/button.md
src/app/layouts/partials/site/scripts.html

- Correct some incorrect variable values
- Bump button font-size for normal buttons from 14px to 16px (1rem)

Variables and Buttons

---

src/alto-ui/Form/Switch/README.md
src/alto-ui/Form/Switch/Switch.js
src/alto-ui/Form/Switch/Switch.scss
src/alto-ui/Form/Switch/index.js
src/alto-ui/Form/Switch/story.js
src/alto-ui/Form/story.js
src/alto-ui/SideNav/SideNav.js
src/alto-ui/SideNav/SideNav.scss
src/alto-ui/SideNav/story.js

Add switch component

---

src/alto-ui/Form/ColorPicker/ColorPicker.js
src/alto-ui/Form/ColorPicker/ColorPicker.scss
src/alto-ui/Form/ColorPicker/story.js
src/alto-ui/scss/variables.scss

Use sass colors for colorpickers

---

src/alto-ui/Form/ColorPicker/story.js
src/alto-ui/Link.js
src/alto-ui/ProvideState.js
src/alto-ui/SideNav/SideNav.js
src/alto-ui/SideNav/SideNav.scss
src/alto-ui/SideNav/story.js
src/alto-ui/scss/variables.scss

| red  | green | blue | purple...|
| - | - | - | - | 
|![image](https://user-images.githubusercontent.com/5002260/36037934-7622c0fa-0dbe-11e8-97f5-1dc83801816b.png)|![image](https://user-images.githubusercontent.com/5002260/36037959-8750d0f6-0dbe-11e8-87cd-cd139a8fd84a.png) | ![image](https://user-images.githubusercontent.com/5002260/36037923-6d38bb66-0dbe-11e8-8930-6c5c92142808.png)|![image](https://user-images.githubusercontent.com/5002260/36037986-978e8c06-0dbe-11e8-935d-99c50078ed4f.png)|

Add colors variations to SideNav

---

src/alto-ui/Button/Button.scss

Fix strange wrapping oon buttons when using other tags

---

package.json
src/alto-ui/Icons/Icon.scss
src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/story.js
yarn.lock

- image
- boolean (bit)
- number
- string
- date

Add basic type formating in Table

---

.storybook/config.js
src/alto-ui/Card/Card.js
src/alto-ui/Card/Card.scss
src/alto-ui/Card/README.md
src/alto-ui/Card/index.js
src/alto-ui/Card/story.js
src/alto-ui/Icons/Image.js
src/alto-ui/Icons/story.js
src/alto-ui/List/story.js
src/alto-ui/MediaObject/MediaObject.js
src/alto-ui/MediaObject/MediaObject.scss
src/alto-ui/MediaObject/README.md
src/alto-ui/MediaObject/index.js
src/alto-ui/MediaObject/story.js
src/alto-ui/ShowMore/README.md
src/alto-ui/ShowMore/ShowMore.js
src/alto-ui/ShowMore/ShowMore.scss
src/alto-ui/ShowMore/index.js
src/alto-ui/ShowMore/story.js

add Cards, ShowMore and MediaObject components

---

package.json
src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Form/DatePicker/DatePicker.scss
src/alto-ui/Form/DatePicker/DatePickerHeader.js
src/alto-ui/Form/DatePicker/README.md
src/alto-ui/Form/DatePicker/index.js
src/alto-ui/Form/DatePicker/story.js
src/alto-ui/Form/FormElement/FormElement.js
src/alto-ui/Form/FormElement/FormElement.scss
src/alto-ui/Form/Label/Label.js
src/alto-ui/Form/Label/Label.scss
src/alto-ui/Form/Select/Select.js
src/alto-ui/Form/TextField/TextField.js
src/alto-ui/Form/story.js
src/alto-ui/Icons/story.js
src/alto-ui/Overlay/Overlay.js
src/alto-ui/Spinner/Spinner.js
src/alto-ui/Spinner/Spinner.scss
src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Tree/Tree.js
yarn.lock

Datepicker & more

---

src/alto-ui/Form/CheckBox/CheckBox.js
src/alto-ui/Form/CheckBox/CheckBox.scss
src/alto-ui/Form/DatePicker/DatePickerHeader.js

feature : Remove styled-component from CheckBox component

---

src/alto-ui/Button/story.js
src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Form/FileInput/story.js
src/alto-ui/Form/Select/story.js
src/alto-ui/Form/TextArea/story.js
src/alto-ui/Form/TextField/story.js
src/alto-ui/helpers/bem.js

Replace some Object.assign by spread object.
No visual impact

Replace Object.assign by spread object

---

src/alto-ui/Breadcrumb/Breadcrumb.js
src/alto-ui/Form/DatePicker/DatePickerHeader.js
src/alto-ui/Pagination/Pagination.js

Replace harcoded label by props in components.
No visual impact.

Replace harcoded label by props in components

---

src/alto-ui/Overlay/Overlay.js
src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/story.js
yarn.lock

Table simple sorting

---

src/alto-ui/Table/Table.scss

Add background-color in table to prepare table full-height

---

src/alto-ui/Breadcrumb/Breadcrumb.js

Fix issue on Breadcrump translation

---

src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/story.js

Table : add filter icon on columns

---

package.json
src/alto-ui/Icons/Error.js
src/alto-ui/Icons/story.js
src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/data.json
src/alto-ui/Table/story.js
yarn.lock

Add calculated fields in table.
- If there is an error, display ErrorIcon and add the error message in title.
- Add title on column name
- Calculated fields display in italic
In the example, Power is a formula between Agility, strength, speed, intelligence

Table : Add calculated fields

---

src/alto-ui/Image.js
src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/TableCell.js
src/alto-ui/Table/data.json
src/alto-ui/Table/story.js

Add avatar with name in table

---

src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Form/DatePicker/story.js

Without readonly
With readonly

DatePicker : manage readOnly props

---

src/alto-ui/Form/DatePicker/DatePicker.scss
src/alto-ui/scss/variables.scss

Fix z-index on DatePicker

---

src/alto-ui/Tree/Tree.js
src/alto-ui/Tree/story.js

When toogle open event on Tree, call onToggle callback

Call onToggle callback on Tree component

---

package.json
src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/TableCell.js
src/alto-ui/Table/data.json
src/alto-ui/Table/story.js
yarn.lock

- Add formaters for date in Table
- Remove date-fns package

Table : Add format field on date

---

src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/TableCell.js
src/alto-ui/Table/data.json

Add formatting float on Table

---

src/alto-ui/SideNav/story.js

Fix propTypes issue in console

Fix label props name

---

src/alto-ui/SideNav/SideNav.scss

Fix margin-left on sideNav icons

---

src/alto-ui/SideNav/SideNav.scss

Remove red hover on sidenav links

---

src/alto-ui/Form/Switch/Switch.scss

Add disabled color on label

---

src/alto-ui/Table/Table.scss
src/alto-ui/Table/data.json

Add max-width to table cells

---

src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/data.json
src/alto-ui/Table/story.js

Table : Manage grouped column

---

src/alto-ui/AltoUIRoot/AltoUIRoot.js
src/alto-ui/Form/Switch/Switch.scss
src/alto-ui/Icons/Bell.js
src/alto-ui/Icons/Download.js
src/alto-ui/Icons/Envelope.js
src/alto-ui/Icons/Icon.js
src/alto-ui/Icons/Icon.scss
src/alto-ui/Icons/story.js
src/alto-ui/SideNav/SideNav.scss
src/alto-ui/SideNav/SideNavPanel.js
src/alto-ui/Spinner/Spinner.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/TableCell.js
src/alto-ui/Tree/Tree.js

Fixes + Icons

---

src/alto-ui/Table/Table.js
src/alto-ui/Table/Table.scss
src/alto-ui/Table/TableContainer.js
src/alto-ui/Table/index.js
src/alto-ui/Table/story.js

Add collapsed on grouped row

---

src/alto-ui/Tabs/Tabs.scss

Smaller tabs

---

src/alto-ui/Table/Table.js
src/alto-ui/Table/TableCell.js
src/alto-ui/Table/TableHeader.js
src/alto-ui/Table/data.json
src/alto-ui/Table/story.js

Table group : Add gouped fields

---

src/alto-ui/Form/FormElement/FormElement.scss
src/alto-ui/Form/FormRow/FormRow.js
src/alto-ui/Form/FormRow/FormRow.scss
src/alto-ui/Form/FormRow/README.md
src/alto-ui/Form/FormRow/index.js

Add FormRow element

---

src/alto-ui/Table/TableCell.js

Display error instead of infinite. Create generic error message

---

.storybook/config.js
src/alto-ui/Button/story.js
src/alto-ui/CloseButton/CloseButton.js
src/alto-ui/CloseButton/CloseButton.scss
src/alto-ui/CloseButton/README.md
src/alto-ui/CloseButton/index.js
src/alto-ui/CloseButton/story.js
src/alto-ui/SideNav/SideNav.scss
src/alto-ui/SideNav/SideNavPanel.js

Close Button for Panels

---

src/alto-ui/Breadcrumb/Breadcrumb.scss

Smaller breadcrumbs

---

src/alto-ui/Button/story.js
src/alto-ui/Icons/Icon.scss

Lessen margins for icon--left and icon--right

---

.storybook/config.js
src/alto-ui/Alert/Alert.scss
src/alto-ui/Table/Table.js
src/alto-ui/Table/TableCell.js

Expose onBlur + provide error in onChange in Table

---

src/alto-ui/Form/Switch/Switch.scss

Darker unchecked state for switch

---

src/alto-ui/Dialog/Dialog.js
src/alto-ui/Dialog/Dialog.scss
src/alto-ui/Dialog/story.js

- Reduce spacing
- Use CloseButton in Header
- Scrollable content

Dialog Improvements

---

src/alto-ui/Icons/ExportFile.js
src/alto-ui/Icons/ImportFile.js
src/alto-ui/Icons/Upload.js
src/alto-ui/Icons/story.js

Add import export upload

---

.storybook/config.js
src/alto-ui/ProgressBar/ProgressBar.js
src/alto-ui/ProgressBar/ProgressBar.scss
src/alto-ui/ProgressBar/README.md
src/alto-ui/ProgressBar/index.js
src/alto-ui/ProgressBar/story.js
src/alto-ui/Tooltip/Tooltip.js
src/alto-ui/Tooltip/Tooltip.scss
src/alto-ui/Tooltip/story.js

<ProgressBar />

---

.storybook/config.js
src/alto-ui/MenuList/MenuList.js
src/alto-ui/MenuList/MenuList.scss
src/alto-ui/MenuList/components/MenuItem.js
src/alto-ui/MenuList/components/MenuItem.scss
src/alto-ui/MenuList/components/MenuItemContainer.js
src/alto-ui/MenuList/index.js
src/alto-ui/MenuList/story.js
src/alto-ui/scss/placeholders.scss

Add MenuList Component

---

.storybook/config.js
src/alto-ui/ProgressCircle/ProgressCircle.js
src/alto-ui/ProgressCircle/ProgressCircle.scss
src/alto-ui/ProgressCircle/README.md
src/alto-ui/ProgressCircle/index.js
src/alto-ui/ProgressCircle/story.js

Add ProgressCircle component

---

src/alto-ui/Table/Table.scss

Fix table header hover bug

---

src/alto-ui/Form/DatePicker/DatePicker.scss
src/alto-ui/Form/DatePicker/DatePickerHeader.js

Fix display on datePicker header

---

src/alto-ui/Table/Table.scss
src/alto-ui/Table/TableCell.js
src/alto-ui/Table/story.js

TableCell : Add warning icon

---

src/alto-ui/Alert/Alert.scss

IE11 Before :
IE 11 After :
Chrome After : 
With long text :

Alert : Fix display issue on ie11

---

src/alto-ui/SideNav/SideNav.js
src/alto-ui/SideNav/SideNav.scss
src/alto-ui/SideNav/story.js

SideNav : Fix display for big title

---

.storybook/Root.js
src/alto-ui/Form/CheckBox/CheckBox.scss
src/alto-ui/Form/FileInput/FileInput.js
src/alto-ui/Form/FileInput/FileInput.scss
src/alto-ui/Form/Radio/Radio.scss
src/alto-ui/Form/Select/Select.scss
src/alto-ui/Form/Switch/Switch.scss
src/alto-ui/Form/TextField/TextField.scss
src/alto-ui/Icons/Icon.scss
src/alto-ui/SideNav/SideNav.scss
src/alto-ui/Tabs/Tabs.scss
src/alto-ui/scss/base.scss
src/alto-ui/scss/mixins.scss
src/alto-ui/scss/placeholders.scss
src/alto-ui/scss/reset.scss
src/alto-ui/scss/variables.scss

Add focus-feedback support  for most the components

---

src/alto-ui/Form/Fieldset/Fieldset.js
src/alto-ui/Form/Fieldset/Fieldset.scss
src/alto-ui/Form/Fieldset/index.js
src/alto-ui/Form/Fieldset/story.js
src/alto-ui/Form/story.js

Form : Add Fieldset component

---

src/alto-ui/Icons/CopyToClipboard.js
src/alto-ui/Icons/index.js

Add new Copy to clipboard icon

---

.storybook/config.js
src/alto-ui/CopyToClipboard/CopyToClipboard.js
src/alto-ui/CopyToClipboard/index.js
src/alto-ui/CopyToClipboard/story.js

Add copy to clipboard component

---

src/alto-ui/Form/Select/Select.scss

Changed select to use Source Sans pro font

---

src/alto-ui/Spinner/Spinner.scss

Change spinner color to blue

---

src/alto-ui/Datagrid/Datagrid.js
src/alto-ui/Datagrid/Datagrid.scss
src/alto-ui/Datagrid/components/DatagridHeaderRow/DatagridHeaderRow.scss

- fix infinite scrolling on static rows
- fix column header sub columns not visible

fix ie11 issues on datagrid

---

.storybook/config.js
src/alto-ui/Menu/Menu.js
src/alto-ui/Menu/Menu.scss
src/alto-ui/Menu/MenuItem.js
src/alto-ui/Menu/README.md
src/alto-ui/Menu/index.js
src/alto-ui/Menu/story.js

Add Menu component

---

src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
src/alto-ui/Form/Select/Select.js
src/alto-ui/Form/Select/Select.scss

cherry-pick https://github.com/beqom/alto/pull/291

DatagridCell : improve display on readonly select

---

src/alto-ui/Popover/Popover.js
src/alto-ui/Popover/Popover.scss
src/alto-ui/Popover/story.js

Add hidePointer and drop shadow to Popover

---

src/alto-ui/SideNav/SideNav.js

SideNav: add Tooltip when the SideNav is collapsed

---

src/alto-ui/Dropdown/Dropdown.js
src/alto-ui/Dropdown/Dropdown.scss
src/alto-ui/Dropdown/components/DropdownItem/DropdownItem.scss
src/alto-ui/Dropdown/story.js
src/alto-ui/Icons/Icon.scss

Add loading to dropdown

---

src/alto-ui/Icons/DragHandle.js
src/alto-ui/Icons/index.js

feature Add DragHandle Icon

---

package.json

Rename scripts like in https://github.com/beqom/alto/pull/346/files

Packags scripts : rename build and watch

---

src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
src/alto-ui/scss/variables.scss

Disabled editable button fields in grid

---

src/alto-ui/Button/Button.scss
src/alto-ui/Dropdown/Dropdown.scss
src/alto-ui/Icons/Icon.scss

- Smaller font-size on small buttons
- Reduced horizontal spacing on flat buttons

Small buttons

---

src/alto-ui/Datagrid/Datagrid.js
src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
src/alto-ui/Datagrid/components/DatagridRow/DatagridRow.js

Better boolean support in datagrid

---

src/alto-ui/Form/InputNumber/InputNumber.js
src/alto-ui/helpers/__tests__/number.test.js
src/alto-ui/helpers/number.js

Better input number

---

src/alto-ui/helpers/formula.js

formula : remove breaking line

---

src/alto-ui/Dropdown/Dropdown.js
src/alto-ui/Dropdown/components/DropdownItem/DropdownItem.js
src/alto-ui/Form/FormElement/FormElement.js
src/alto-ui/Form/Label/Label.js
src/alto-ui/Form/Select/Select.js
src/alto-ui/Form/Select/Select.scss
src/alto-ui/Form/Select/SelectDropdown.js
src/alto-ui/Form/Select/SelectNative.js
src/alto-ui/Form/Select/story.js
src/alto-ui/RelativeBox/RelativeBox.js
src/alto-ui/scss/variables.scss

- Use Dropdown for Select
- Support Multi select

Use Dropdown for default Select

---

src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Form/DatePicker/DatePicker.scss
src/alto-ui/Form/DatePicker/DatePickerHeader.js
src/alto-ui/Overlay/Overlay.js
src/alto-ui/Popover/Popover.js

- Use Popover in DatePicker
- Use new Select 
- cleanup

Use Popover in DatePicker

---

.storybook/config.js
src/alto-ui/Input/Input.js
src/alto-ui/Input/Input.scss
src/alto-ui/Input/README.md
src/alto-ui/Input/index.js
src/alto-ui/Input/story.js

It's a generic input component that take a type and render the appropriate form element.

Create a <Input /> component

---

src/alto-ui/Dropdown/Dropdown.js
src/alto-ui/Form/Select/Select.scss
src/alto-ui/Form/Select/SelectDropdown.js

- SelectDropdown: add disable state
- Dropdown: fix open function

Fix issues on SelectDropdown and Dropdown

---

src/alto-ui/Datagrid/Datagrid.js
src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.scss
src/alto-ui/Datagrid/components/DatagridCellInput/index.js
src/alto-ui/Datagrid/components/DatagridRow/DatagridRow.js

- Remove input from DatagridCell
- add date and boolean support

Split DatagridCell + support more input type

---

src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Form/Select/SelectDropdown.js

- Fix display issue for Date format in DatePicker
- Fix display issue for Trigger in SelectDropdown

Fix display issues in SelectDropdown and DatePicker

---

src/alto-ui/Tree/Tree.js
src/alto-ui/Tree/components/TreeItem/TreeItem.js
src/alto-ui/Tree/components/TreeItem/TreeItem.scss
src/alto-ui/Tree/components/TreeItem/TreeItemContainer.js
src/alto-ui/Tree/story.js

Add Chrildren limit per page to Tree

---

src/alto-ui/Datagrid/Datagrid.js
src/alto-ui/Datagrid/Datagrid.scss
src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
src/alto-ui/Datagrid/components/DatagridGroupedRow/DatagridGroupedRow.js
src/alto-ui/Datagrid/components/DatagridGroupedRow/DatagridGroupedRow.scss
src/alto-ui/Datagrid/components/DatagridHeaderCell/DatagridHeaderCell.js

Fix Datagrid grouped row

---

src/alto-ui/Datagrid/Datagrid.scss

34611 - fix Edge scrolling bars

---

src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js

Fix column width that is editable.

Fix editable column width - move styles to container

---

src/alto-ui/Form/Select/Select.scss

Added hide on clearable, only showing it on hover

Added hide on clearable, only showing it on hover

---

src/alto-ui/Form/DatePicker/DatePicker.scss
src/alto-ui/Form/InputNumber/InputNumber.js
src/alto-ui/Form/InputNumber/InputNumber.scss
src/alto-ui/Form/TextField/TextField.scss

Added new max width for inputs

---

src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Form/Select/Select.scss
src/alto-ui/Form/TextField/TextField.js
src/alto-ui/Form/TextField/TextField.scss
src/alto-ui/Popover/Popover.scss
src/alto-ui/helpers/position.js
src/alto-ui/scss/variables.scss

Ajust inputs style

---

src/alto-ui/Icons/Icon.js
src/alto-ui/Icons/Icon.scss

Add active prop and styles to icon

---

src/alto-ui/Icons/DragHandle.js

Add new data for DragHandle icon

---

.storybook/config.js
src/alto-ui/ContentEditable/ContentEditable.js
src/alto-ui/ContentEditable/index.js
src/alto-ui/ContentEditable/story.js

Add ContentEditable component

---

src/alto-ui/ContentEditable/ContentEditable.js
src/alto-ui/Form/TextField/TextField.js
src/alto-ui/GhostInput/GhostInput.js
src/alto-ui/GhostInput/GhostInput.scss
src/alto-ui/GhostInput/story.js

Use contenteditable in GhostInput

---

.storybook/config.js
package.json
src/alto-ui/Sortable/README.md
src/alto-ui/Sortable/Sortable.js
src/alto-ui/Sortable/Sortable.scss
src/alto-ui/Sortable/index.js
src/alto-ui/Sortable/story.js
src/alto-ui/scss/base.scss
src/alto-ui/scss/placeholders.scss
yarn.lock

Add Sortable component

---

src/alto-ui/Icons/Dashboard.js
src/alto-ui/Icons/index.js

Icons : add dashboard

---

src/alto-ui/Icons/Content.js
src/alto-ui/Icons/index.js

feature/Add Content Icon

---

src/alto-ui/Icons/Templates.js
src/alto-ui/Icons/index.js

feature/Add Templates Icon

---

src/alto-ui/Icons/Details.js
src/alto-ui/Icons/index.js

feature/Add Details Icon

---

src/alto-ui/Form/Label/Label.scss

Font weight reduced from 700 to 600

Design update to label input

---

src/alto-ui/Icons/AngleArrow.js
src/alto-ui/Icons/index.js

Add AngleArrow icon

---

src/alto-ui/hooks/useEventListener.js

- Add event lsitener manually that will be removed onUnmount.
- usefull for global event listener on document

add useEventListener hook

---

.storybook/config.js
src/alto-ui/Tag/Tag.js
src/alto-ui/Tag/Tag.scss
src/alto-ui/Tag/index.js
src/alto-ui/Tag/story.js

Add Tag component

---

.storybook/config.js
src/alto-ui/Aside/Aside.js
src/alto-ui/Aside/Aside.scss
src/alto-ui/Aside/index.js
src/alto-ui/Aside/story.js
src/alto-ui/CloseButton/CloseButton.js

Create Aside component

---

src/alto-ui/Form/TagInput/TagInput.js
src/alto-ui/Form/TagInput/TagInput.scss
src/alto-ui/Form/TagInput/helpers.js
src/alto-ui/Form/TagInput/hooks/usePosition.js
src/alto-ui/Form/TagInput/hooks/useSelectionKeyboardNav.js
src/alto-ui/Form/TagInput/hooks/useTagInputStateAndRefs.js
src/alto-ui/Form/TagInput/index.js
src/alto-ui/Form/TagInput/story.js
src/alto-ui/Form/TextField/index.js
src/alto-ui/Form/story.js
src/alto-ui/Input/Input.js
src/alto-ui/hooks/useResettableState.js

Add TagInput component

---

src/alto-ui/Form/CheckBox/CheckBox.js
src/alto-ui/Form/CheckBox/CheckBox.scss
src/alto-ui/Form/CheckBox/__tests__/CheckBox.test.js
src/alto-ui/Form/InputNumber/InputNumber.js
src/alto-ui/Form/Radio/Radio.js
src/alto-ui/Form/Radio/Radio.scss
src/alto-ui/Icons/Icon.js

* checkbox and radio:
* use same api (props) and behavior
* label is now only the width of the text
* icons:
* use active state

Small UI fixes

---

package.json
src/alto-ui/Form/CheckBox/CheckBox.scss
src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Form/InputNumber/InputNumber.js
src/alto-ui/Form/Radio/Radio.scss
src/alto-ui/helpers/__tests__/number.test.js
src/alto-ui/helpers/number.js
yarn.lock

- Add InputNumber min/max
- Add iso/timestamp format to datePicker
- Fix checkbox/radio position

Add InputNumber min/max + Add iso/timestamp format to datePicker

---

src/alto-ui/scss/variables.scss

lighter border color

---

src/alto-ui/Dialog/Dialog.js
src/alto-ui/Form/TagInput/TagInput.js
src/alto-ui/Overlay/Overlay.js
src/alto-ui/Overlay/Overlay.scss
src/alto-ui/Sortable/Sortable.js
src/alto-ui/Sortable/story.js

Rewiewing commit by commit make probably more sense here.
- Change Sortable onChange handler params
- remove "isRequired" for closeTargetId  …
- Filter falsy values in TagInput
- remove click outside when blocking in Overlay

Small fixes

---

src/alto-ui/Form/InputNumber/InputNumber.js
src/alto-ui/Form/InputNumber/story.js
src/alto-ui/Form/TextField/TextField.js
src/alto-ui/helpers/number.js

ticket: https://bqmcloudrepository.visualstudio.com/App/_workitems/edit/36779

Feature#36779 - InputNumber should support percentage

---

src/alto-ui/Form/Select/Select.scss
src/alto-ui/Form/TextField/TextField.js
src/alto-ui/Form/TextField/TextField.scss

BUG#36781 - ReadOnly prop should remove "focus", "hover" etc style

---

src/alto-ui/Form/TextField/TextField.scss
src/alto-ui/Header/Header.scss

changed letter spacing in the header title

---

src/alto-ui/Datagrid/Datagrid.js
src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
src/alto-ui/Datagrid/components/DatagridRow/DatagridRow.js

Add DatagridCell--summary class to Total Row

BugFix# 36895 -Add class DatagridCell--summary to total row cells

---

src/alto-ui/Form/CheckBox/CheckBox.js
src/alto-ui/Form/CheckBox/CheckBox.scss
src/alto-ui/Form/Radio/Radio.js
src/alto-ui/Form/Radio/Radio.scss
src/alto-ui/Form/TextField/TextField.scss

Bugfix#36781 - changed cursor behavior for form inputs

---

src/alto-ui/Icons/Divider.js
src/alto-ui/Icons/index.js

feature - add divider icon

---

src/alto-ui/Form/DatePicker/DatePicker.js

added editing for DatePicker

---

src/alto-ui/Datagrid/Datagrid.scss

Change group header checkbox column background color to white

---

src/alto-ui/Icons/Horizontal.js
src/alto-ui/Icons/Vertical.js
src/alto-ui/Icons/index.js

Add horizontal and Vertical icons

---

package.json
src/alto-ui/Datagrid/Datagrid.js
src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Form/InputNumber/InputNumber.js
src/alto-ui/Form/InputNumber/story.js
src/alto-ui/Form/TextField/TextField.js
src/alto-ui/helpers/number.js
yarn.lock

add percent props handling to component InputNumber
cherrypicks
#583  #595

Move InputNumber percentage to 0.13 v

---

README.md

Added build status to README file

---

src/alto-ui/Datagrid/Datagrid.scss
src/alto-ui/Datagrid/components/DatagridHeaderRow/DatagridHeaderRow.scss

Fixed from https://github.com/beqom/alto/pull/606

Datagrid: fix horizontal missalignment and horizontal scroll

---

src/alto-ui/Form/Select/SelectDropdown.js

https://github.com/beqom/alto/pull/619

v0.13 Added tooltip for inputs in data grid

---

src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js

https://github.com/beqom/alto/pull/626

bugfix DatagridCell: shouldUpdate

---

src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Input/Input.js

- fix pick a number
- fix editing when value was ""

fix datepicker input

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js

If checkbox has initial checked value it doesn't display

fixed default checked state for checkbox input

---

src/alto-ui/Form/RichTextEditor/RichTextEditor.js
src/alto-ui/Input/Input.js
src/alto-ui/hooks/useDebouncedCallback.js
src/alto-ui/hooks/useFocusInOut.js

- cancel setState on useFocusInOut on umount
- useDebouncedCallback: use the last callback
- Transform Input into function with hooks
- allow mentions if content is empty

Allow mentions on empty richtext + other fixes

---

src/alto-ui/Form/InputNumber/InputNumber.js
src/alto-ui/Form/TextField/TextField.js

Fix InputNumber's FormElement size

---

src/alto-ui/Form/RichTextEditor/RichTextEditor.js

Use FormElement in RichText

---

src/alto-ui/Input/Input.js

Fix lagging input

---

src/alto-ui/Card/Card.js
src/alto-ui/Card/Card.scss
src/alto-ui/Card/__tests__/Card.test.js
src/alto-ui/Card/story.js
src/alto-ui/Sortable/story.js

feature Card: refactor and accept dragHandelProps and actions

---

src/alto-ui/Card/Card.scss

- Reduce padding
- Remove flex on body element
Before 
After

Card reduce padding top and bottom on body element

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Form/DatePicker/DatePicker.js

cherry-pick of https://github.com/beqom/alto/pull/653

bugfix DatePicker: handle errors

---

src/alto-ui/RelativeBox/RelativeBox.js

https://github.com/beqom/alto/pull/663

0.17 - bugfix - add condition in componentDidUpdate to prevent infinite loop

---

src/alto-ui/scss/placeholders.scss

cherry-pick of https://github.com/beqom/alto/pull/669

VisuallyHidden: fix top display issue when using checkboxes

---

.storybook/config.js
src/alto-ui/HTMLBlock/HTMLBlock.js
src/alto-ui/HTMLBlock/story.js

- Rewrite href with good url
- Add target _blank on links

HTMLBlock - Manage url with and without http

---

src/alto-ui/RelativeBox/RelativeBox.js

- Use hooks instead of class
- Fix misaligment thanks to the `useLayoutEffect` hook https://github.com/beqom/alto/pull/677/files#diff-3076d42cc32a07baf32d333ccbd77ca2R99
No visual change.

Refactor Relative Box with hooks

---

src/alto-ui/RelativeBox/RelativeBox.js

https://github.com/beqom/alto/pull/677

bugfix BQM-786 RelativeBox: refactor to fix regression on position

---

src/alto-ui/Form/Switch/Switch.js
src/alto-ui/Form/Switch/Switch.scss
src/alto-ui/Form/Switch/story.js

- Rewrite from scratch
- improve animation
- improve overall style
- add small modifier

Refactor Switch component

---

src/alto-ui/Image.js

 Refactor Image with hooks

---

src/alto-ui/Tooltip/Tooltip.js

Refactor Tooltip with hooks

---

src/alto-ui/Sortable/Sortable.js
src/alto-ui/Sortable/story.js
src/alto-ui/helpers/guid.js
src/alto-ui/hooks/useUniqueKey.js

- Allow to nest <Sortable /> component
- Create a useUniqueKey that generate a new key if the key passed in parametter does not exist. It can be usefull for needed but optionnal html ids or key to store data by component. Dont use it for iteration keys.

Nested Sotable

---

.storybook/config.js
src/alto-ui/Badge/Badge.js
src/alto-ui/Badge/Badge.scss
src/alto-ui/Badge/index.js
src/alto-ui/Badge/story.js

Add Badge component

---

src/alto-ui/Avatar/Avatar.js
src/alto-ui/Avatar/Avatar.scss
src/alto-ui/Avatar/__tests__/Avatar.test.js
src/alto-ui/Avatar/story.js

- Improve sizes
- Add tooltip
Before | After
-|-

Improve Avatar sizes

---

src/alto-ui/Icons/Icon.js
src/alto-ui/Icons/__tests__/Icon.test.js
src/alto-ui/Icons/story.js

- merge style passed in props
- add new weight feature
0 (default)|1|2|3|5
-|-|-|-|-

Support weight and style in Icon

---

src/alto-ui/Card/Card.js
src/alto-ui/Card/Card.scss
src/alto-ui/Card/__tests__/Card.test.js
src/alto-ui/Group/useGroupItem.js

use Actions in Card + support grouping

---

src/alto-ui/List/List.js
src/alto-ui/Sortable/Sortable.js
src/alto-ui/Sortable/Sortable.scss
src/alto-ui/Sortable/story.js

Support disabled items in Sortable

---

src/alto-ui/Sortable/story.js

fix sortable story

---

src/alto-ui/List/List.js
src/alto-ui/List/List.scss

`fields` -> `fields(item)`
`nestedItemsKey ` -> `nestedItemsKey(item)`

Allow to pass some function in props in List

---

src/alto-ui/Datagrid/components/DatagridGroupedRow/DatagridGroupedRow.js

https://github.com/beqom/alto/pull/704

Bugfix - Grouping using ID not name (#704)

---

src/alto-ui/Tree/components/TreeItem/TreeItem.scss

UI Internet Explorer not tree arrows

---

src/alto-ui/Datagrid/components/DatagridHeaderCell/DatagridHeaderCell.js

Check more props changes in `shouldComponentUpdate` in `DataGridHeaderCell`

Improve should component update in DataGridHeader

---

src/alto-ui/Icons/CaretDown.js
src/alto-ui/Icons/CaretLeft.js
src/alto-ui/Icons/CaretRight.js
src/alto-ui/Icons/CaretUp.js
src/alto-ui/Icons/index.js
src/alto-ui/Icons/story.js

Add Caret icons + add a search in icons all story

---

src/alto-ui/Form/TextField/TextField.js
src/alto-ui/Form/TextField/TextField.scss
src/alto-ui/Form/TextField/story.js

Custumize rendering of Texfield + clearable

---

src/alto-ui/Media/Media.js
src/alto-ui/Media/Media.scss
src/alto-ui/Media/story.js

Media can be active

---

src/alto-ui/Datagrid/Datagrid.js

https://github.com/beqom/alto/pull/726

bugfix Datagrid: disabled checkbox without key

---

src/alto-ui/Form/Typeahead/Typeahead.js
src/alto-ui/Form/Typeahead/story.js

Now you pass an id as value and object as item.

Support ids as value for typeahead

---

src/alto-ui/Form/Typeahead/Typeahead.js
src/alto-ui/Form/Typeahead/Typeahead.scss
src/alto-ui/Form/Typeahead/story.js

- Add loading state
- keep the typed value in memory and diplay it only on focus

Add loading to typeahead

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.scss
src/alto-ui/Form/FormElement/FormElement.js
src/alto-ui/Form/Select/Select.js
src/alto-ui/Form/Select/story.js
src/alto-ui/Form/TextField/TextField.scss
src/alto-ui/Form/Typeahead/Typeahead.js
src/alto-ui/Form/Typeahead/index.js

Add Typeahead as default for Select

---

src/alto-ui/Form/FormElement/FormElement.js
src/alto-ui/Form/Typeahead/Typeahead.js
src/alto-ui/Form/Typeahead/Typeahead.scss
src/alto-ui/Form/Typeahead/story.js

Add pagination to typeahead

---

src/alto-ui/Form/TextField/TextField.scss

fix textarea width/padding/placeholder

---

src/alto-ui/Form/Typeahead/Typeahead.js
src/alto-ui/Form/Typeahead/Typeahead.scss

fix select on typeahead issue

---

src/alto-ui/SideNav/SideNav.js
src/alto-ui/SideNav/SideNav.scss
src/alto-ui/SideNav/story.js

**This is only first step to rebuild that component**
Update of sidenav:
- add secondaryItems that will be displayed on the bottom of side nav

feature/Modify SideNav and add secondary items

---

package.json
src/alto-ui/scss/variables.scss

feature/ Bump to v.0.20.4

---

src/alto-ui/scss/base.scss

Bugfix remove X from ie search input

---

src/alto-ui/Dialog/Dialog.js

Dialog: add id on first div

---

src/alto-ui/Form/TextField/TextField.scss

IE11 : drop down list icon not displayed 

---

src/alto-ui/Datagrid/Datagrid.scss

https://github.com/beqom/alto/pull/757

bugfix - ms browsers - set overflow style to scrollbar

---

src/alto-ui/Pagination/Pagination.js

Remove unnecessary `openFocusTargetId`

bugfix/Fix pagination on IE

---

src/alto-ui/SideNav/SideNav.scss

Without this settings sidenav cause appear of double scrollbar on small screen

Fix toggle button in Side nav

---

src/alto-ui/Button/Button.js

An error was throwing in the console.

Bugfix Button: Large props was missing in buttonProps

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Form/DatePicker/DatePicker.js

Datepicker should close on enter key

close datepicker on enter key

---

src/alto-ui/Icons/Pergamen.js
src/alto-ui/Icons/index.js

New pergamen icon

---

src/alto-ui/Form/Typeahead/Typeahead.js

added test id for typehead carret

feature - added test id for typehead carret

---

src/alto-ui/Icons/Camera.js

added camera icon

---

src/alto-ui/List/List.js

Fix list with Badges - check elementProps function

bugfix/Fix List with badges

---

src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js

enhancement - datagrid - add tooltip in info fields

---

src/alto-ui/Image.js

added support for onerror and onload image events

feature added onerror and onload service for image component

---

src/alto-ui/Form/CheckBox/CheckBox.js
src/alto-ui/Form/CheckBox/CheckBox.scss

with label | without label
-|-

1rem * 1rem checkbox if no label displayed

---

src/alto-ui/Datagrid/Datagrid.js
src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js

https://github.com/beqom/alto/pull/787

feature DatagridCell: support visibility

---

src/alto-ui/Form/DatePicker/DatePicker.js

Date picker was not clearable.

bugfix - fixed clear input for datepicker

---

src/alto-ui/Form/TextField/TextField.js
src/alto-ui/Form/TextField/TextField.scss
src/alto-ui/Form/Typeahead/Typeahead.scss

(cherry picked from commit b37b7b6dc4ea6b40c30e42f865636467bb8c79c5)

0.13 - bugfix ie issue on fields size (#789)

---

package.json
src/alto-ui/scss/variables.scss

Release v0.20.17

---

src/alto-ui/SideNav/SideNav.js

added possibility to setup outline for sidenav icons

feature - added possibility to setup outline for sidenav icons

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Form/DatePicker/DatePicker.js

On change date for datepicker not everything have been as should.
In some cases datepicker didn't close, in other didn't set date.
This is fix for that.

bugfix - fixed set value on change date for datepicker in dropdown

---

src/alto-ui/Form/DatePicker/DatePicker.js

fixed select month, year and time in date picker

bugfix/BQM-2179 fixed select month, year and time in date picker

---

src/alto-ui/Form/DatePicker/DatePicker.js
src/alto-ui/Form/DatePicker/DatePickerHeader.js

added possibility to empty value for year in datepicker

added possibility to empty value for year in datepicker

---

src/alto-ui/Form/Typeahead/Typeahead.js
src/alto-ui/Form/Typeahead/story.js

Fix value on typeahead and loadmore

Typeahead fix

---

src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss

(cherry picked from commit 3dc64ac0ad26b1eb4625e3d9cd15446e7e40bf03)

Bugfix - Active row needs to have white inputs (#875)

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Form/DatePicker/DatePicker.js

added labels ( translations ) for datepickers

added labels ( translations ) for datepickers

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Form/Typeahead/Typeahead.js

On Chrome: 
- Fixed blinking dropdown after click on input
On IE:
- Fixed clicking on scrollbar
- Fixed stucking typeahead dropdown
- Fixed losting focus on input

Bugfix - IE11 - Fixed stucking typeahead dropdown

---

package.json
src/alto-ui/scss/variables.scss

Release v0.21.6

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Form/Typeahead/Typeahead.js

Bugfix - Fix typeahead load more

---

azure-pipelines.yml

add sonarqube

---

azure-pipelines.yml

add sonarqube 0.20

---

azure-pipelines.yml

Add sonar on 0.13

---

azure-pipelines.yml

add sonar on 0.10

---

package.json
src/alto-ui/scss/variables.scss

- Typeahead onBlur / onClose fix

Release v0.21.8

---

src/alto-ui/Form/Typeahead/Typeahead.js

Difference between master and 0.20

Filter Not Working when select invisible element on first page

---

src/alto-ui/Datagrid/Datagrid.js
src/alto-ui/Datagrid/Datagrid.scss
src/alto-ui/helpers/__tests__/sum.test.js
src/alto-ui/helpers/navigator.js
src/alto-ui/helpers/sum.js
src/alto-ui/scss/variables.scss

fixes for lagging scroll on process and fix IE11 performance

---

src/alto-ui/List/List.js
src/alto-ui/Media/Media.js

Bugfix - Clickthrough condition added to the List component

---

src/alto-ui/Form/Typeahead/Typeahead.js

Typeahead - clear search on clear input

---

src/alto-ui/Datagrid/Datagrid.js

https://github.com/beqom/alto/pull/921

hotfix - error add event listener on datagrid

---

src/alto-ui/Avatar/Avatar.js

Avatar accepts now a custom icon

---

src/alto-ui/Form/CheckBox/CheckBox.scss

Align Vertically Checkbox without-label

---

src/alto-ui/SideNav/SideNav.js
src/alto-ui/SideNav/SideNav.scss

If user is on same section return div, if not return a link

feature SideNave: disable click if user is already on section

---

src/alto-ui/Datagrid/components/DatagridCellInput/__tests__/DatagridCellInput.test.js

tests for DataGridCellInput

---

src/alto-ui/Datagrid/components/DatagridHeaderCell/DatagridHeaderCell.js
src/alto-ui/Datagrid/components/DatagridHeaderCell/DatagridHeaderCellContent.js
src/alto-ui/Datagrid/components/DatagridHeaderCell/__tests__/DataGridHeaderCellContent.test.js
src/alto-ui/Datagrid/components/DatagridHeaderCell/__tests__/DatagridHeaderCell.test.js

enhancement - refactor DatagridHeaderCell

---

src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/__tests__/getBooleanProps.test.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/__tests__/getDateProps.test.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/__tests__/getListProps.test.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/__tests__/getNumberProps.test.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/__tests__/getSharedProps.test.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/__tests__/getTextProps.test.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/getBooleanProps.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/getDateProps.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/getListProps.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/getNumberProps.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/getSharedProps.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/getTextProps.js
src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInputAdapters/index.js
src/alto-ui/Datagrid/components/DatagridCellInput/__tests__/DatagridCellInput.test.js
src/alto-ui/Datagrid/helpers.js

refactor-for-DataGridCellInput

refactor-for-DataGridCellInput

---

src/alto-ui/Dialog/__tests__/Dialog.test.js

Added tests for a Dialog
